[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
evm_version = 'cancun'
solc_version = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 200