[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
evm_version = 'cancun'
solc_version = "0.8.28"
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [
    { access = "read", path = "./out" }
]
optimizer = true
optimizer_runs = 200

[lint]
severity = ["high"]
exclude_lints = ["incorrect-shift"]
